version: "3.9"

services:

  nginx:
    image: nginx:latest
    container_name: mage2_nginx
    ports:
      - "80:80"
    volumes:
      - ./magento2:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - mage2_net

  app:
    build:
      context: ./docker/app
    container_name: mage2_app
    volumes:
      - ./magento2:/var/www/html
    depends_on:
      - db
      - search
      - redis
    networks:
      - mage2_net

  db:
    image: mariadb:10.6
    container_name: mage2_db
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mage2_net

  redis:
    image: redis:alpine
    container_name: mage2_redis
    networks:
      - mage2_net

  search:
    image: opensearchproject/opensearch:2.11.0
    container_name: mage2_search
    environment:
      discovery.type: single-node
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
      plugins.security.disabled: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search_data:/usr/share/opensearch/data
    networks:
      - mage2_net

volumes:
  db_data:
  search_data:

networks:
  mage2_net:
    driver: bridge
